#!/usr/bin/env python
"""
	@author: Jean-Lou Dupont
"""
import os
import sys

## for development environment
this_dir=os.path.dirname(__file__)
lib_path=os.path.abspath(os.path.join(this_dir, ".."))
sys.path.insert(0, lib_path)

from jld_scripts.scripts.id3info import main

main()
