#!/usr/bin/env python
"""
	@author: Jean-Lou Dupont
"""
## for development environment
import os
import sys

if "JLD_SCRIPTS" in os.environ:
	this_dir=os.path.dirname(__file__)
	lib_path=os.path.abspath(os.path.join(this_dir, ".."))
	sys.path.insert(0, lib_path)
	
from jld_scripts.scripts.lastfm_gettracks import main

try:
	main()
except KeyboardInterrupt:
	print "\nExiting..."
	sys.exit(1)

